name: gt
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10=hecd8cb5_0
  - certifi=2022.12.7=py37hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=1.1.1t=hca72f7f_0
  - pip=22.3.1=py37hecd8cb5_0
  - python=3.10
  - readline=8.2=hca72f7f_0
  - setuptools=65.6.3=py37hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - wheel=0.38.4=py37hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - anyio==3.7.0
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attr==0.3.2
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - black==23.3.0
    - bleach==6.0.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cycler==0.11.0
    - dataclasses==0.6
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - exceptiongroup==1.1.1
    - fastjsonschema==2.17.1
    - filelock==3.12.2
    - fonttools==4.38.0
    - fsspec==2023.1.0
    - fuzzywuzzy==0.18.0
    - gt-pyg==0.0.0
    - huggingface-hub==0.15.1
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - jupyter-server==1.24.0
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.4.4
    - markupsafe==2.1.3
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.4.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.21.6
    - packaging==23.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.11.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.6.0
    - powerlaw==1.5
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pytdc==0.4.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.1.0
    - rdkit==2023.3.1
    - rdkit-pypi==2022.9.5
    - requests==2.31.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.1
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typed-ast==1.5.4
    - typing-extensions==4.6.3
    - urllib3==2.0.2
    - versioneer==0.28
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - websocket-client==1.5.2
    - weightwatcher==0.7.1.5
    - zipp==3.15.0
